[package]
name = "avila-gui"
description = "Native egui interface for Avila Node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
avila-core.workspace = true
avila-node.workspace = true
avila-consensus.workspace = true
avila-p2p.workspace = true
clap.workspace = true
eframe.workspace = true
serde.workspace = true

[lints]
workspace = true
